### ISSUE TITLE
Provide an example `output.csv` test file

### ISSUE THREAD

**Issue by beeb** [unconv/csvfind#7]
It would be nice to share the CSV file that was used for tests. If it can be generated by a script, that would be even better.

**Comment by unconv** [comment]
Hi! The `output.csv` that is used in the tests is generated by copying the contents of `products.csv` into `output.csv` 10,000 times with the `csvcopy.c` script in the repo. I added a mention of this to the README.

**Comment by beeb** [comment]
Thanks, but the products.csv file does not contain "winkpad"

**Comment by unconv** [comment]
Oops, I forgot about that... I just changed the last ThinkPad to WinkPad (in the `output.csv` file after copying the lines from `products.csv` into it)

**Comment by beeb** [comment]
I proposed a simple script to generate the final output file in my PR https://github.com/unconv/csvfind/pull/8
